### ISSUE TITLE
Translate missing phrase to Spanish

### ISSUE THREAD

**Issue by jsi** [enonic/app-applications#110]
There is one phrase missing a Spanish translation:
 - market.installingApp

**Comment by Blask0** [comment]
https://github.com/enonic/app-applications/pull/118 done.

**Comment by jsi** [comment]
Hi @Blask0 !
Thanks for your work!  The change has been merged and commited!

**Comment by Blask0** [comment]
No problem. Sorry for the late replies, i was busy. I will do the other ones soon.

**Comment by jsi** [comment]
We are just very grateful that you can do this.  We really appreciate it.

FYI: We are close to finishing our "test-and-bugfix-phase" for v7.2.0, so we expect the release next week.  The release will happen whether or not all translations are in place.  We have had problems getting Spanish translated for the past year, so for both 7.0.0 and 7.1.0, phrases were missing for Spanish.  To get them in place now is really great!
If you don't have time to translate everything before we make the release, they will come in the next release, which is not a problem.
