### ISSUE TITLE
ActionMenu on Statistic Panel should be closed, when an application was unselected

### ISSUE THREAD

**Issue by sgauruseu** [enonic/app-applications#13]
1. Open `Applications`, select an application 
2. Click on `drop-down-button` in Action menu(Statistic Panel)
3. Click on the row and unselect  the application
4. Click on other row with an application

Expected:  Action menu  should be collapsed
Actual:    Menu is expanded

![apps](https://user-images.githubusercontent.com/3728712/39123339-408643d8-4700-11e8-8aa9-62a08d37c301.png)

**Comment by edloidas** [comment]
Issue moved to [enonic/lib-admin-ui #575](https://github.com/enonic/lib-admin-ui/issues/575) via [**ZenHub**](https://www.zenhub.com/)
