### ISSUE TITLE
Selection Controller remains checked after uninstalling applications.

### ISSUE THREAD

**Issue by sgauruseu** [enonic/app-applications#145]
1. Select 3 applications.
2. Click on Uninstall button, confirm this action.

BUG: SelectionController remains checked and Selection toggler is visible after uninstalling selected applications.  Preview Panel is not cleared.
![image](https://user-images.githubusercontent.com/3728712/85000758-86cddc80-b15b-11ea-8d37-b8f2edea9391.png)

**Click on Show Selection:**
![image](https://user-images.githubusercontent.com/3728712/85004812-a9162900-b160-11ea-9e25-260427bcd0f3.png)

**Comment by ashklianko** [comment]
Not reproduced anymore
