### ISSUE TITLE
Tiny blogs looks weird

### ISSUE THREAD

**Issue by ComLock** [enonic/app-applications#1671]
![Screenshot 2024-04-15 at 12 31 36](https://github.com/enonic/app-applications/assets/118847/738595bd-b6d5-4a54-984f-7e0cdbb46ee5)

**Comment by ComLock** [comment]
In contentstudio aswell
![Screenshot 2024-04-15 at 12 31 53](https://github.com/enonic/app-applications/assets/118847/91124d9d-8418-44c5-94ab-5d7bc9c02b73)

**Comment by alansemenov** [comment]
Fixed in the app: https://github.com/enonic/app-tiny-blog/commit/af95c847aebb09b8e897cfee82c762f2972b8546
