### ISSUE TITLE
Increase install request timeout

### ISSUE THREAD

**Issue by edloidas** [enonic/app-applications#1773]
Sometimes, the internet connection can be slow, or communication between XP servers and the provider may not be fast enough. When a user uploads a large application (such as our Cloud API, which is 30MB), the current 30-second timeout is insufficient. The user won't even see a proper timeout error. Instead, they only see an empty red error notification and a yellow notification stating that the app wasn't installed.

* Increase timeout to at least 60 seconds.
* Improve the error message: There should only be one error message, clearly stating that a timeout occurred, rather than displaying an empty message.

The reason this is considered a bug is that it prevents users from successfully uploading the app, even though there is no actual issue with the app or the upload process itself.

**Comment by rymsha** [comment]
there is no timeout for app install in app-applications
upload size/timeout is set in Load Balancer and/or Proxy
