### ISSUE TITLE
Support readonly mode

### ISSUE THREAD

**Issue by rymsha** [enonic/app-applications#203]
app-applications should have a configuration flag to effectively work in read only mode.
All of the action buttons in the toolbar (Install, Uninstall, Start and Stop) should then be invisible.

**Comment by alansemenov** [comment]
Do you have a use-case example? Shouldn't this be based on permissions, like "App Administrator" role that can install/uninstall apps while regular user cannot?

**Comment by rymsha** [comment]
this is not about users, it is in general when XP comes with preinstalled apps we may want to disable installing new ones via app-applications.

**Comment by alansemenov** [comment]
ok, do we want one setting for both install and uninstall or two different ones? also, is it allowed to start/stop apps but not install/uninstall?

**Comment by sigdestad** [comment]
This is for Enonic Cloud, to prevent users from installing apps directly in Enonic XP. It would probably be smart if Install button was available, but that modal says this is a managed instance, and to contact your system administrator or similar

**Comment by alansemenov** [comment]
Ok, I can see this is far from being a ready task description, definitely not "Current Sprint". I'll set "To Be Discussed" label on this until we decide how this should work/look.

**Comment by alansemenov** [comment]
@ashklianko Call config `readonlyMode`. It has to be implicitly set to `true`, any other value or missing config should be treated as `false` (like [here](https://github.com/enonic/app-contentstudio/blob/master/src/main/resources/admin/tools/main/main.js#L11)).

When `app-applications` is in readonly mode:
* All buttons in the toolbar should be hidden
* No checkbox in the grid's toolbar
* No checkbox column in the grid
* No context menu on right-click in the grid
* Disabled (or hidden) action dropdown in the Application Statistics panel

Also check that no actions are visible in the mobile mode.
