### ISSUE TITLE
Fix aesthetics when app-applications is in readonly mode.

### ISSUE THREAD

**Issue by gbbirkisson** [enonic/app-applications#254]
Now when you put app-applications in read only mode, the actionbar is replaced by a white empty bar. Can it not just remove the bar all together?

![app-applications](https://i.imgur.com/lUJomeu.png)

**Comment by rymsha** [comment]
It is a nice place where we can write ~~"We are wasting space - get lost!"~~ "Applications are managed externally."

**Comment by sigdestad** [comment]
I suggest the following:
<img width="711" alt="Screenshot 2020-12-04 at 10 43 57" src="https://user-images.githubusercontent.com/482228/101148250-b1cebe80-361d-11eb-9350-3b36f42b8f22.png">
