### ISSUE TITLE
Market is not working in QA or Prod.

### ISSUE THREAD

**Issue by jsi** [enonic/app-applications#28]
In Prod and QA, clicking the "Install" button to open the list of apps to install, only produce an infinite waiting screen:
![screenshot 2018-07-24 15 27 07](https://user-images.githubusercontent.com/477453/43141436-2987c15e-8f56-11e8-9070-6d2245e27924.png)

Looking at the network traffic, it appears as if a request to market is made, and a result is returned, but for some reason, the result is not processed correctly in the App.

When I first upgraded QA and production to 6.15.0, this was not a problem.  The only change since then, which I know of, that may have caused this, is adding the 7.0.0 tag to some of the apps on the market.  Maybe the processing of version numbers is not working as it should?  For instance, the Chuck Norris App, xpDoctor and the Content Viewer, all have recieved 7.0.0 as a version tag.  Also, the SuperHero App have a new version that works with 7.0.0.  -  Finally, I have also downloaded the distro of 6.15.0, and run it locally.  This is not a problem either.

**Comment by alansemenov** [comment]
@jsi Install app dialog works fine on a clean installation of 6.15 in Google Cloud launcher. Can it be something with prod/QA configuration?
