### ISSUE TITLE
Used By in Item Statistics panel is not refreshed after deleting/adding content in Content Studio

### ISSUE THREAD

**Issue by sgauruseu** [enonic/app-applications#305]
1. Go to Applications and select `Features`  
2. Go to Content Studio and delete Features site
3. Go to Applications

**BUG**   `Used By` data group should not be displayed

![image](https://user-images.githubusercontent.com/3728712/105967656-27439200-6097-11eb-8124-4c9f32b166dc.png)

Refresh app browse panel in browser page - this data group gets not visible.

**Comment by alansemenov** [comment]
We should check if it's possible to listen to content events in this app. If not, we shouldn't spend time on trying to fix this.
