### ISSUE TITLE
Change header in the App info panel to indicate that site is coming from the default project

### ISSUE THREAD

**Issue by sgauruseu** [enonic/app-applications#306]
1. Install SuperHero project
2. Go to `default` context and open new site wizard, select SuperHero in app-selector and save this site.
3. Go to Application and select Super Hero app.

BUG - SuperHero site is not displayed in Used by data group

![image](https://user-images.githubusercontent.com/3728712/105975280-d4220d00-609f-11eb-8242-e4a00949a610.png)

**Comment by alansemenov** [comment]
@sgauruseu We cannot show sites from other repositories because app-users doesn't know anything about CMS repositories. For now we will simply change the header to indicate that displayed site is taken from the default project.
