### ISSUE TITLE
Install apps dialog: all apps are loaded on shown

### ISSUE THREAD

**Issue by ashklianko** [enonic/app-applications#41]
Apps supposed to be loaded when scrolling down close to last element in grid, however when dialog is open all apps are loaded sequentially

**Comment by ashklianko** [comment]
Best option is to get rid off grid in this dialog: https://github.com/enonic/app-applications/issues/44

**Comment by alansemenov** [comment]
No longer relevant after https://github.com/enonic/app-applications/issues/449
