### ISSUE TITLE
Application Item Statistics Panel - panel is not refreshed after changing a selection in the grid. Incorrect state is displayed in the panel

### ISSUE THREAD

**Issue by sgauruseu** [enonic/app-applications#414]
1. Go to `Applications` and select `Features` 

**BUG**: -  Incorrect state of the application in the statistics panel 
![image](https://user-images.githubusercontent.com/3728712/127125293-2018135d-b598-4c96-93a8-73c37cfaee46.png)

2.  Select `Content Studio` in the grid.
**BUG**: - Application Item Statistics Panel is not updated

![image](https://user-images.githubusercontent.com/3728712/127125433-488a3a3f-6296-4ec9-9b12-cd6f25da0249.png)

**Comment by ashklianko** [comment]
Issue moved to [enonic/lib-admin-ui #2077](https://github.com/enonic/lib-admin-ui/issues/2077) via [**ZenHub**](https://www.zenhub.com/)
