### ISSUE TITLE
Install app dialog won't get refreshed after app install/uninstall

### ISSUE THREAD

**Issue by alansemenov** [enonic/app-applications#585]
Regression after https://github.com/enonic/app-applications/issues/540

The list of applications in the Install app dialog is now requested and rendered once and that is great. But installation status of apps in the list won't get updated when installed apps are uninstalled or an earlier version of an app is installed.

To reproduce:

Case 1:
1. Open the Install app dialog
2. Close it
3. Uninstall one of the apps
4. Reopen the dialog and scroll to the one you have uninstalled. It still says "**Installed**" but should've been "**Install**".

Case 2:
1. Open the Install app dialog
2. Install an earlier version of one of the apps that you don't have yet **via direct link from the repo**
3. Reopen the dialog and scroll to the app you have installed
4. The button says "**Install**" but should've said "**Update**" since the version you have is earlier than the one on the Market

**Comment by edloidas** [comment]
There is also one more issue: if the dialog is opened right after the page is opened (the market apps have not been loaded yet in the background), the apps with Update status won't be shown on top.

Also, it may be useful to update the dialog on server events, when the app was installed/uninstalled from another tab/instance. It wasn't implemented yet.
