### ISSUE TITLE
App Matomo can be installed even if the current version is up to date

### ISSUE THREAD

**Issue by poi33** [enonic/app-applications#857]
![image](https://user-images.githubusercontent.com/3340349/184089108-f42064e5-953d-4126-bd89-3390dd6f36f8.png)

While version 1.1.0 is installed it still possible to install the same version 1.1.0. 

Also possibly related, there was no update button when there was a newer version. 
Just an install button like on the picture.

**Comment by sgauruseu** [comment]
The same issue with  `Edit button` , `Azure AD ID Provider`, `Code Highlighting Macro`....
Install link is always displayed in the modal dialog for some applications, even if these applications are already installed

**Comment by alansemenov** [comment]
Was caused by https://github.com/enonic/site-market/issues/303
